### PR TITLE
Updated to Spring Boot 1.3.2.RELEASE

### PR DESCRIPTION
**Pull request by edwardmlyte**

### CODE REVIEW

**Comment by gregturn** [comment]
Looks great! Have you signed the Spring CLA? https://support.springsource.com/spring_committer_signup

**Comment by edwardmlyte** [comment]
Not yet, which project would this be classified under? Spring boot?

**Comment by gregturn** [comment]
Spring Boot is fine.

**Comment by edwardmlyte** [comment]
Signed, sealed, delivered.

**Comment by gregturn** [comment]
Thanks!

**Pull request merged**
