### PR TITLE
Fixes to support several OAuth 2 Grants

### PR DESCRIPTION
**Pull request by frankolschewski**
There are some fixes required to support some OAuth 2 Grants.
Note: Even after the fixes this is NOT a fully-fledged OAuth 2 Authorization Server, because some (verry important) features are already not working, like Authorization Code Grant and Login with Resource Owner Credentials.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@frankolschewski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-boot-oauth2&pullRequestId=73)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-spring-boot-oauth2&pullRequestId=73) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@frankolschewski Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-boot-oauth2&pullRequestId=73)!

**Comment by dsyer** [comment]
AFAIK this sample only ever supported auth code grants (that was kind of the point of it). And there was no user locally because it was a “social” login via github or Facebook. It seems like this change might have missed the point of the sample, given that the comment says that auth code doesn’t work. Or maybe I don’t get it?

**Comment by frankolschewski** [comment]
Sorry, I made a mistake and made myself unclear (I adjusted the README).
First of all, nothing has been broken by my changes. Everything that worked before continues to work now (the social login with Authorization Code Grant).
Spring Boot always created a local user automatically at startup. By explicitly setting the credentials, we can now use it for the Resource Owner Password Credentials Grant.
I wrote "Authorization Code Grant is NOT working", that's wrong. The Authorization Code Grant is working.
The sample code is great, but it is NOT a fully-fledged OAuth Authorization Server. But with my changes, he almost is. The only missing part is the local login with user name and password.
Let's add the missing local login and this example can be used by everyone to program a complete OAuth 2 server with spring boot.

**Comment by dsyer** [comment]
Sorry, but I think that’s out of scope for this guide. There are plenty of other auth server samples around, so I don’t think we need to implement all the features in the spec in this one.

**Pull request closed without merging**
