### PR TITLE
Correct annotationname of @EnableOAuth2Client in the readme

### PR DESCRIPTION
**Pull request by derTobsch**
@EnableOAuthClient -> @EnableOAuth2Client

### CODE REVIEW

**Comment by dsyer** [comment]
Fixed in 824f418, thanks.

**Comment by derTobsch** [comment]
I think you mean 17a3cb3a3a074bfe38f8e568cdb19d3c4e00db58 :-)

**Comment by dsyer** [comment]
Looks like it. Thanks again.

**Comment by derTobsch** [comment]
Are no other contributors allowed or why did you not merge my request?

**Comment by dsyer** [comment]
It was trivial. I didn't want to bother you to ask if you'd filled in the CLA.

**Pull request closed without merging**
